name: Deploy sloths.rs.school
on:
  push:
    branches: [master]
    paths:
      - 'tools/sloths/**'
      - '.github/workflows/deploy-sloths.yaml'

concurrency:
  group: deploy-sloths
  cancel-in-progress: true

jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/sloths
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore npm cache
        uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Build
        run: npm run build-only

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          AWS_DEFAULT_REGION: eu-central-1
        run: aws s3 cp dist s3://sloths.rs.school/ --recursive --cache-control "public,max-age=15552000,immutable"
