# This is a basic workflow to help you get started with Actions

name: Deploy Client

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache .next
        uses: actions/cache@v2
        env:
          cache-name: cache-next
        with:
          path: ./client/src/.next/cache/
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Test (npm test)
        run: |
          npm test
        working-directory: ./client

      - name: Build (npm run build)
        run: |
          npm run build
        working-directory: ./client

      - name: Clean modules
        working-directory: ./client
        run: |
          npm ci --production --no-optional

      - name: Build container
        working-directory: ./client
        run: |
          docker build -t ghcr.io/rolling-scopes/rsschool-app-client:master .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish container
        working-directory: ./client
        run: |
          docker push ghcr.io/rolling-scopes/rsschool-app-client:master
